import { Locatie } from './types'

export const LOCATIES: Locatie[] = [
  { id: 'texel-de-koog', naam: 'Texel De Koog', lat: 53.107, lng: 4.756, type: 'kust', regio: 'nl-kust' },
  { id: 'den-helder', naam: 'Den Helder', lat: 52.959, lng: 4.756, type: 'kust', regio: 'nl-kust' },
  { id: 'bergen-aan-zee', naam: 'Bergen aan Zee', lat: 52.668, lng: 4.588, type: 'kust', regio: 'nl-kust' },
  { id: 'egmond-aan-zee', naam: 'Egmond aan Zee', lat: 52.618, lng: 4.617, type: 'kust', regio: 'nl-kust' },
  { id: 'castricum-aan-zee', naam: 'Castricum aan Zee', lat: 52.562, lng: 4.600, type: 'kust', regio: 'nl-kust' },
  { id: 'zandvoort', naam: 'Zandvoort', lat: 52.372, lng: 4.533, type: 'kust', regio: 'nl-kust' },
  { id: 'noordwijk', naam: 'Noordwijk', lat: 52.244, lng: 4.440, type: 'kust', regio: 'nl-kust' },
  { id: 'katwijk-aan-zee', naam: 'Katwijk aan Zee', lat: 52.202, lng: 4.398, type: 'kust', regio: 'nl-kust' },
  { id: 'scheveningen', naam: 'Scheveningen', lat: 52.106, lng: 4.272, type: 'kust', regio: 'nl-kust' },
  { id: 'kijkduin', naam: 'Kijkduin', lat: 52.069, lng: 4.216, type: 'kust', regio: 'nl-kust' },
  { id: 'hoek-van-holland', naam: 'Hoek van Holland', lat: 51.978, lng: 4.124, type: 'kust', regio: 'nl-kust' },
  { id: 'rockanje', naam: 'Rockanje', lat: 51.879, lng: 4.054, type: 'kust', regio: 'nl-kust' },
  { id: 'ouddorp', naam: 'Ouddorp', lat: 51.824, lng: 3.900, type: 'kust', regio: 'nl-kust' },
  { id: 'renesse', naam: 'Renesse', lat: 51.726, lng: 3.773, type: 'kust', regio: 'zeeland' },
  { id: 'domburg', naam: 'Domburg', lat: 51.564, lng: 3.499, type: 'kust', regio: 'zeeland' },
  { id: 'westkapelle', naam: 'Westkapelle', lat: 51.523, lng: 3.440, type: 'kust', regio: 'zeeland' },
  { id: 'vlissingen', naam: 'Vlissingen', lat: 51.441, lng: 3.571, type: 'kust', regio: 'zeeland' },
  { id: 'grevelingen-brouwersdam', naam: 'Grevelingen Brouwersdam', lat: 51.742, lng: 3.889, type: 'estuarium', regio: 'zeeland' },
  { id: 'veerse-meer', naam: 'Veerse Meer', lat: 51.561, lng: 3.680, type: 'estuarium', regio: 'zeeland' },
  { id: 'oosterschelde-zeelandbrug', naam: 'Oosterschelde Zeelandbrug', lat: 51.626, lng: 3.898, type: 'estuarium', regio: 'zeeland' },
  { id: 'yerseke', naam: 'Yerseke', lat: 51.496, lng: 4.056, type: 'estuarium', regio: 'zeeland' },
  { id: 'westerschelde-borsele', naam: 'Westerschelde Borsele', lat: 51.408, lng: 3.757, type: 'estuarium', regio: 'zeeland' },
  { id: 'den-helder-haven', naam: 'Den Helder Haven', lat: 52.960, lng: 4.760, type: 'waddenzee', regio: 'waddenzee' },
  { id: 'harlingen', naam: 'Harlingen', lat: 53.174, lng: 5.424, type: 'waddenzee', regio: 'waddenzee' },
  { id: 'vlieland', naam: 'Vlieland', lat: 53.298, lng: 4.914, type: 'waddenzee', regio: 'waddenzee' },
  { id: 'terschelling', naam: 'Terschelling', lat: 53.360, lng: 5.218, type: 'waddenzee', regio: 'waddenzee' },
  { id: 'de-panne-be', naam: 'De Panne', lat: 51.107, lng: 2.590, type: 'kust', regio: 'be-kust' },
  { id: 'koksijde-be', naam: 'Koksijde', lat: 51.117, lng: 2.652, type: 'kust', regio: 'be-kust' },
  { id: 'oostende-be', naam: 'Oostende', lat: 51.229, lng: 2.916, type: 'kust', regio: 'be-kust' },
  { id: 'de-haan-be', naam: 'De Haan', lat: 51.270, lng: 3.034, type: 'kust', regio: 'be-kust' },
  { id: 'blankenberge-be', naam: 'Blankenberge', lat: 51.313, lng: 3.133, type: 'kust', regio: 'be-kust' },
  { id: 'knokke-heist-be', naam: 'Knokke-Heist', lat: 51.356, lng: 3.296, type: 'kust', regio: 'be-kust' },
]
